### PR TITLE
Refactor TypeScript definition to CommonJS compatible export

### PR DESCRIPTION
**Pull request by BendingBender**
**Breaking change**.

### CODE REVIEW

**Comment by cmdcolin** [comment]
@BendingBender maybe I'm missing something but in 4.0.0 it appears I'd do a default import but it results in errors from TypeScript
```
import QuickLRU from 'quick-lru'
```

```
error TS1192: Module '"/home/mymodule/node_modules/quick-lru/index"' has no default export.                                                                    

6 import QuickLRU from 'quick-lru'
```

**Comment by sindresorhus** [comment]
Read the release notes: https://github.com/sindresorhus/quick-lru/releases/tag/v4.0.0

**Comment by cmdcolin** [comment]
Ah thanks. I guess even with this I get this error

```
SyntaxError: `import =` is not supported by @babel/plugin-transform-typescript
```

If I added allowSyntheticDefaultImports to tsconfig.json and then `import QuickLRU from 'quick-lru'` then it did seem to work with quick-lru@4.0.0

**Comment by BendingBender** [comment]
I recommend using the `esModuleInterop` flag, it's the more modern variant of `syntheticDefaultImports`, it'll work even without Babel.
